// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm5IPsYIU8nWkbKUQWWMaJypzKmcNktgQ',
    appId: '1:396885943884:web:b00fbd04030eab24d136e9',
    messagingSenderId: '396885943884',
    projectId: 'employee-report-87335',
    authDomain: 'employee-report-87335.firebaseapp.com',
    storageBucket: 'employee-report-87335.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBykMC_2OnZ67sp_-yAKsc7mGPjivSUIA',
    appId: '1:396885943884:android:3f7c7472df348b25d136e9',
    messagingSenderId: '396885943884',
    projectId: 'employee-report-87335',
    storageBucket: 'employee-report-87335.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI1H57dw9r-XFw1Lqy5wSk2p4Od0lRua4',
    appId: '1:396885943884:ios:637cb31d2c7ed652d136e9',
    messagingSenderId: '396885943884',
    projectId: 'employee-report-87335',
    storageBucket: 'employee-report-87335.appspot.com',
    iosBundleId: 'com.employeeattendance.employeeAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI1H57dw9r-XFw1Lqy5wSk2p4Od0lRua4',
    appId: '1:396885943884:ios:637cb31d2c7ed652d136e9',
    messagingSenderId: '396885943884',
    projectId: 'employee-report-87335',
    storageBucket: 'employee-report-87335.appspot.com',
    iosBundleId: 'com.employeeattendance.employeeAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm5IPsYIU8nWkbKUQWWMaJypzKmcNktgQ',
    appId: '1:396885943884:web:091627e512a5917bd136e9',
    messagingSenderId: '396885943884',
    projectId: 'employee-report-87335',
    authDomain: 'employee-report-87335.firebaseapp.com',
    storageBucket: 'employee-report-87335.appspot.com',
  );
}
